// Author: Martin Murin (martin.murin@cern.ch)
// 
// This macro plots observables from LHE events
// 
// The purpose of this study is to identify four top event observables
// sensitive to the CP property of the top-Higgs coupling
//
// This code is a plotting tool for event observables from ROOT files
// containing events in LHE format generated by MadGraph

// ROOT headers
///#include<TROOT.h>
///#include<TSystem.h>
///#include<TFile.h>
///#include<TChain.h>

// ExRootAnalysis headers
#include<ExRootAnalysis/ExRootTreeReader.h>
#include<ExRootAnalysis/ExRootTreeBranch.h>
#include<ExRootAnalysis/ExRootLHEFReader.h>
#include<ExRootAnalysis/ExRootClasses.h>
//#include</afs/cern.ch/work/m/mmurin/public/ExRootAnalysis/ExRootAnalysis/ExRootTreeReader.h>
//#include</afs/cern.ch/work/m/mmurin/public/ExRootAnalysis/ExRootAnalysis/ExRootTreeBranch.h>
//#include</afs/cern.ch/work/m/mmurin/public/ExRootAnalysis/ExRootAnalysis/ExRootLHEFReader.h>
//#include</afs/cern.ch/work/m/mmurin/public/ExRootAnalysis/ExRootAnalysis/ExRootClasses.h>

// Delphes headers
#include<classes/DelphesClasses.h>

// C++ libraries
#include<iostream>
#include<algorithm>
#include<cmath>
#include<numeric>
#include<string>
#include<vector>

// This program
#include<LocalTools.h>
#include<Cuts.h>
#include<GeneralPlot.h>
#include<Observables.h>
#include<ObservablesTruthJetMatch.h>
#include<TChainsMaker.h>
#include<TruthEvent4Top.h>
#include<GenTopParticle.h>

void processPartonsFromMadGraph(std::string productionName, std::string sample, std::string yukawa, std::string obsFilePath){
    // Initialize event chains
    std::vector<std::string> chainsNames;
    std::vector<TChain*> chains;

    //TChain chain_kt_0_alpha_0("LHEF");
    TChain chain_kt_1_alpha_0("LHEF");
    TChain chain_kt_2_alpha_0("LHEF");
    TChain chain_kt_5_alpha_0("LHEF");
    TChain chain_kt_1_alpha_45("LHEF");
    TChain chain_kt_1_alpha_90("LHEF");

    SampleSet sampleSet = samplemap.find(sample)->second;
    YukawaSet yukawaSet = yukawamap.find(yukawa)->second;

    switch (yukawaSet){
        case YukawaSet::kappa:
            // Used for sensitivity to top-Yukawa coupling strengths
            chainsNames = {"kt_1_alpha_0", "kt_2_alpha_0", "kt_5_alpha_0"};
            //create_chain_kt_0_alpha_0(chain_kt_0_alpha_0, sampleSet);
            create_chain_kt_1_alpha_0(chain_kt_1_alpha_0, sampleSet);
            create_chain_kt_2_alpha_0(chain_kt_2_alpha_0, sampleSet);
            create_chain_kt_5_alpha_0(chain_kt_5_alpha_0, sampleSet);

            //chains_kt.push_back(& chain_kt_0_alpha_0);
            chains.push_back(& chain_kt_1_alpha_0);
            chains.push_back(& chain_kt_2_alpha_0);
            chains.push_back(& chain_kt_5_alpha_0);
            break;

        case YukawaSet::alpha:
            // Used for sensitivity to top-Yukawa coupling CP property
            chainsNames = {"kt_1_alpha_0", "kt_1_alpha_45", "kt_1_alpha_90"};
            create_chain_kt_1_alpha_0(chain_kt_1_alpha_0, sampleSet);
            create_chain_kt_1_alpha_45(chain_kt_1_alpha_45, sampleSet);
            create_chain_kt_1_alpha_90(chain_kt_1_alpha_90, sampleSet);

            chains.push_back(& chain_kt_1_alpha_0);
            chains.push_back(& chain_kt_1_alpha_45);
            chains.push_back(& chain_kt_1_alpha_90);
            break;
    }

    // Set up observables into a vector 
    std::vector<std::unique_ptr<GeneralPlot>> observablesVec;
    
    observablesVec.emplace_back(new Obs_m_tttt(productionName, sampleSet, yukawaSet, chainsNames));
    observablesVec.emplace_back(new Obs_m_tttt_boosted(productionName, sampleSet, yukawaSet, chainsNames));
    observablesVec.emplace_back(new Obs_m_tt(productionName, sampleSet, yukawaSet, chainsNames));
    observablesVec.emplace_back(new Obs_m_tbartbar(productionName, sampleSet, yukawaSet, chainsNames));
    observablesVec.emplace_back(new Obs_mht_mhtbar(productionName, sampleSet, yukawaSet, chainsNames));
    observablesVec.emplace_back(new Obs_eta_tt(productionName, sampleSet, yukawaSet, chainsNames));
    observablesVec.emplace_back(new Obs_eta_tbartbar(productionName, sampleSet, yukawaSet, chainsNames));
    observablesVec.emplace_back(new Obs_phi_tt(productionName, sampleSet, yukawaSet, chainsNames));
    observablesVec.emplace_back(new Obs_phi_tbartbar(productionName, sampleSet, yukawaSet, chainsNames));
    observablesVec.emplace_back(new Obs_phi_ttbar(productionName, sampleSet, yukawaSet, chainsNames));
    observablesVec.emplace_back(new Obs_phi_ttbar_min(productionName, sampleSet, yukawaSet, chainsNames));
    observablesVec.emplace_back(new Obs_phi_ttbar_max(productionName, sampleSet, yukawaSet, chainsNames));
    observablesVec.emplace_back(new Obs_phi_ttbar_avg(productionName, sampleSet, yukawaSet, chainsNames));
    observablesVec.emplace_back(new Obs_phi_HiggsTTInOtherTTFrame(productionName, sampleSet, yukawaSet, chainsNames));
    observablesVec.emplace_back(new Obs_phi_HiggsTTInOtherTTFrameVectorial(productionName, sampleSet, yukawaSet, chainsNames));
    observablesVec.emplace_back(new Obs_dy_tt(productionName, sampleSet, yukawaSet, chainsNames));
    observablesVec.emplace_back(new Obs_dy_tbartbar(productionName, sampleSet, yukawaSet, chainsNames));
    observablesVec.emplace_back(new Obs_dy_ttbar_all(productionName, sampleSet, yukawaSet, chainsNames));
    observablesVec.emplace_back(new Obs_dy_ttbar_min(productionName, sampleSet, yukawaSet, chainsNames));
    observablesVec.emplace_back(new Obs_dy_ttbar_max(productionName, sampleSet, yukawaSet, chainsNames));
    observablesVec.emplace_back(new Obs_dy_ttbar_avg(productionName, sampleSet, yukawaSet, chainsNames));
    observablesVec.emplace_back(new Obs_b2_tt(productionName, sampleSet, yukawaSet, chainsNames));
    observablesVec.emplace_back(new Obs_b2_txtx(productionName, sampleSet, yukawaSet, chainsNames));
    observablesVec.emplace_back(new Obs_b4_tt(productionName, sampleSet, yukawaSet, chainsNames));
    observablesVec.emplace_back(new Obs_b4_txtx(productionName, sampleSet, yukawaSet, chainsNames));
    observablesVec.emplace_back(new Obs_b2_ttbar(productionName, sampleSet, yukawaSet, chainsNames));
    observablesVec.emplace_back(new Obs_b4_ttbar(productionName, sampleSet, yukawaSet, chainsNames));
    observablesVec.emplace_back(new Obs_b2_ttbar_boosted(productionName, sampleSet, yukawaSet, chainsNames));
    observablesVec.emplace_back(new Obs_b4_ttbar_boosted(productionName, sampleSet, yukawaSet, chainsNames));
    observablesVec.emplace_back(new Obs_cosPhiC(productionName, sampleSet, yukawaSet, chainsNames));
    observablesVec.emplace_back(new Obs_HT(productionName, sampleSet, yukawaSet, chainsNames));
    observablesVec.emplace_back(new Obs_dR_ttbar_min(productionName, sampleSet, yukawaSet, chainsNames));
    observablesVec.emplace_back(new Obs_dR_ttbar_avg(productionName, sampleSet, yukawaSet, chainsNames));
    observablesVec.emplace_back(new Obs_dRtt(productionName, sampleSet, yukawaSet, chainsNames));
    observablesVec.emplace_back(new Obs_dRtxtx(productionName, sampleSet, yukawaSet, chainsNames));
    observablesVec.emplace_back(new Obs_dR_ttbar_lead_min(productionName, sampleSet, yukawaSet, chainsNames));
    observablesVec.emplace_back(new Obs_leadingTopPT(productionName, sampleSet, yukawaSet, chainsNames));
    observablesVec.emplace_back(new Obs_diffHiLoTopPT(productionName, sampleSet, yukawaSet, chainsNames));
    observablesVec.emplace_back(new Obs_leadingBeautyPT(productionName, sampleSet, yukawaSet, chainsNames));
    observablesVec.emplace_back(new Obs_leadingLeptonPT(productionName, sampleSet, yukawaSet, chainsNames));
    observablesVec.emplace_back(new Obs_subleadingTopPT(productionName, sampleSet, yukawaSet, chainsNames));
    observablesVec.emplace_back(new Obs_leadingTopEta(productionName, sampleSet, yukawaSet, chainsNames));
    observablesVec.emplace_back(new Obs_leadingBeautyEta(productionName, sampleSet, yukawaSet, chainsNames));
    observablesVec.emplace_back(new Obs_leadingLeptonEta(productionName, sampleSet, yukawaSet, chainsNames));
    observablesVec.emplace_back(new Obs_m_ttbar_minDR(productionName, sampleSet, yukawaSet, chainsNames));
    observablesVec.emplace_back(new Obs_m_ttbar_leadPT_minDR(productionName, sampleSet, yukawaSet, chainsNames));
    observablesVec.emplace_back(new Obs_b2_ttbar_minDR_boosted(productionName, sampleSet, yukawaSet, chainsNames));
    observablesVec.emplace_back(new Obs_b4_ttbar_minDR_boosted(productionName, sampleSet, yukawaSet, chainsNames));
    observablesVec.emplace_back(new Obs_b2_ttbar_leadPT_minDR_boosted(productionName, sampleSet, yukawaSet, chainsNames));
    observablesVec.emplace_back(new Obs_b4_ttbar_leadPT_minDR_boosted(productionName, sampleSet, yukawaSet, chainsNames));
    observablesVec.emplace_back(new Obs_b1_ttbar_leadPT_minDR_boosted(productionName, sampleSet, yukawaSet, chainsNames));
    observablesVec.emplace_back(new Obs_a1_ttbar_leadPT_minDR_boosted(productionName, sampleSet, yukawaSet, chainsNames));
    observablesVec.emplace_back(new Obs_pT_ttbar_max(productionName, sampleSet, yukawaSet, chainsNames));
    observablesVec.emplace_back(new Obs_pT_ttbar_minDR(productionName, sampleSet, yukawaSet, chainsNames));
    observablesVec.emplace_back(new Obs_eta_ttbar_all(productionName, sampleSet, yukawaSet, chainsNames));
    observablesVec.emplace_back(new Obs_eta_ttbar_min(productionName, sampleSet, yukawaSet, chainsNames));
    observablesVec.emplace_back(new Obs_eta_ttbar_max(productionName, sampleSet, yukawaSet, chainsNames));
    observablesVec.emplace_back(new Obs_eta_ttbar_avg(productionName, sampleSet, yukawaSet, chainsNames));
    observablesVec.emplace_back(new Obs_thetaStar(productionName, sampleSet, yukawaSet, chainsNames));
    observablesVec.emplace_back(new Obs_angleTopAntitopPlanes(productionName, sampleSet, yukawaSet, chainsNames));
    observablesVec.emplace_back(new Obs_tripleProductLeadingTopPTFrame(productionName, sampleSet, yukawaSet, chainsNames));
    observablesVec.emplace_back(new Obs_p1Xp2Op3Xp4(productionName, sampleSet, yukawaSet, chainsNames));
    observablesVec.emplace_back(new Obs_p1Xp3Op2Xp4(productionName, sampleSet, yukawaSet, chainsNames));
   
    // Variables to be written into the TTree
    typedef struct {
        Double_t m_tttt;
        Double_t m_tt;
        Double_t m_tbartbar;
        Double_t m_ttbar_minDR;
        Double_t m_ttbar_leadPT_minDR;
        Double_t eta_tt;
        Double_t eta_tbartbar;
        Double_t eta_ttbar_min;
        Double_t eta_ttbar_max;
        Double_t eta_ttbar_avg;
        Double_t dy_tt;
        Double_t dy_tbartbar;
        Double_t dy_ttbar_min;
        Double_t dy_ttbar_max;
        Double_t dy_ttbar_avg;
        Double_t phi_tt;
        Double_t phi_tbartbar;
        Double_t phi_ttbar_min;
        Double_t phi_ttbar_max;
        Double_t phi_ttbar_avg;
        Double_t ht;
        Double_t dR_ttbar_min;
        Double_t dR_ttbar_avg;
        Double_t dRtt;
        Double_t dRtxtx;
        Double_t leadingTopPT;
        Double_t diffHiLoTopPT;
        Double_t b2_tt;
        Double_t b4_tt;
        Double_t b2_txtx;
        Double_t b4_txtx;
        Double_t b2_ttbar_leadPT_minDR_boosted;
        Double_t b4_ttbar_leadPT_minDR_boosted;
        Double_t pT_ttbar_max;
        Double_t pT_ttbar_minDR;
        Double_t tripleProductLeadingTopPTFrame;
        Double_t dR_ttbar_lead_min;
        Int_t    train_score;
    } EventObservables;
    
    // Helper function to extract the value of a given observable from the vector of observables
    auto grabObsValue = [&observablesVec](const char* name){
        auto it = std::find_if(
                observablesVec.begin(),
                observablesVec.end(),
                [&name](const std::unique_ptr<GeneralPlot>& obs){
                    return std::string(obs->pltparams.name) == std::string(name);
                }
            );
        if (it != std::end(observablesVec)){
            return (*it)->fillObservable;
        }
        else{
            return 0.;
        }
    };

    TFile *hfile = TFile::Open(obsFilePath.c_str(),"RECREATE"); 
    vector<TChain*>::iterator iTChain;

    // Iterate over the event chains (coupling strengths or CP-mixing angles)
    for(iTChain = chains.begin(); iTChain != chains.end(); iTChain++){
        int idxChain = iTChain - chains.begin();
        cout << "processing " << chainsNames.at(idxChain) << " ("  << idxChain+1 << "/" << chainsNames.size() << ")\n";

        ExRootTreeReader *treeReaderChainKt = new ExRootTreeReader(*iTChain);
        Long64_t nEntriesChainKt = treeReaderChainKt->GetEntries();

        std::cout << "nEntriesChainsKt " << nEntriesChainKt << "\n";
        TClonesArray *branchParticles = treeReaderChainKt->UseBranch("Particle");
        
        // Prepare output TTree
        EventObservables eventObsInputBDT;
        TTree *eventObsTree = new TTree(chainsNames.at(idxChain).c_str(), "Observables for BDT input");
        eventObsTree->Branch("m_tttt",          &eventObsInputBDT.m_tttt,           "m_tttt/D");
        eventObsTree->Branch("m_tt",            &eventObsInputBDT.m_tt,             "m_tt/D");
        eventObsTree->Branch("m_tbartbar",      &eventObsInputBDT.m_tbartbar,       "m_tbartbar/D");
        eventObsTree->Branch("m_ttbar_minDR",   &eventObsInputBDT.m_ttbar_minDR,    "m_ttbar_minDR/D");
        eventObsTree->Branch("m_ttbar_leadPT_minDR",    &eventObsInputBDT.m_ttbar_leadPT_minDR,     "m_ttbar_leadPT_minDR/D");
        eventObsTree->Branch("eta_tt",          &eventObsInputBDT.eta_tt,           "eta_tt/D");
        eventObsTree->Branch("eta_tbartbar",    &eventObsInputBDT.eta_tbartbar,     "eta_tbartbar/D");
        eventObsTree->Branch("eta_ttbar_min",   &eventObsInputBDT.eta_ttbar_min,    "eta_ttbar_min/D");
        eventObsTree->Branch("eta_ttbar_max",   &eventObsInputBDT.eta_ttbar_max,    "eta_ttbar_max/D");
        eventObsTree->Branch("eta_ttbar_avg",   &eventObsInputBDT.eta_ttbar_avg,    "eta_ttbar_avg/D");
        eventObsTree->Branch("phi_tt",          &eventObsInputBDT.phi_tt,           "phi_tt/D");
        eventObsTree->Branch("phi_tbartbar",    &eventObsInputBDT.phi_tbartbar,     "phi_tbartbar/D");
        eventObsTree->Branch("phi_ttbar_min",   &eventObsInputBDT.phi_ttbar_min,    "phi_ttbar_min/D");
        eventObsTree->Branch("phi_ttbar_max",   &eventObsInputBDT.phi_ttbar_max,    "phi_ttbar_max/D");
        eventObsTree->Branch("phi_ttbar_avg",   &eventObsInputBDT.phi_ttbar_avg,    "phi_ttbar_avg/D");
        eventObsTree->Branch("dy_tt",           &eventObsInputBDT.dy_tt,            "dy_tt/D");
        eventObsTree->Branch("dy_tbartbar",     &eventObsInputBDT.dy_tbartbar,      "dy_tbartbar/D");
        eventObsTree->Branch("dy_ttbar_min",    &eventObsInputBDT.dy_ttbar_min,     "dy_ttbar_min/D");
        eventObsTree->Branch("dy_ttbar_max",    &eventObsInputBDT.dy_ttbar_max,     "dy_ttbar_max/D");
        eventObsTree->Branch("dy_ttbar_avg",    &eventObsInputBDT.dy_ttbar_avg,     "dy_ttbar_avg/D");
        eventObsTree->Branch("ht",              &eventObsInputBDT.ht,               "ht/D");
        eventObsTree->Branch("dR_ttbar_min",    &eventObsInputBDT.dR_ttbar_min,     "dR_ttbar_min/D");
        eventObsTree->Branch("dR_ttbar_avg",    &eventObsInputBDT.dR_ttbar_avg,     "dR_ttbar_avg/D");
        eventObsTree->Branch("dRtt",            &eventObsInputBDT.dRtt,             "dRtt/D");
        eventObsTree->Branch("dRtxtx",          &eventObsInputBDT.dRtxtx,           "dRtxtx/D");
        eventObsTree->Branch("leadingTopPT",    &eventObsInputBDT.leadingTopPT,     "leadingTopPT/D");
        eventObsTree->Branch("pT_ttbar_max",    &eventObsInputBDT.pT_ttbar_max,     "pT_ttbar_max/D");
        eventObsTree->Branch("pT_ttbar_minDR",  &eventObsInputBDT.pT_ttbar_minDR,   "pT_ttbar_minDR/D");
        eventObsTree->Branch("diffHiLoTopPT",   &eventObsInputBDT.diffHiLoTopPT,    "diffHiLoTopPT/D");
        eventObsTree->Branch("dR_ttbar_lead_min",       &eventObsInputBDT.dR_ttbar_lead_min,        "dR_ttbar_lead_min/D");
        eventObsTree->Branch("b2_tt",           &eventObsInputBDT.b2_tt,            "b2_tt/D");
        eventObsTree->Branch("b2_txtx",         &eventObsInputBDT.b2_txtx,          "b2_txtx/D");
        eventObsTree->Branch("b4_tt",           &eventObsInputBDT.b4_tt,            "b4_tt/D");
        eventObsTree->Branch("b4_txtx",         &eventObsInputBDT.b4_txtx,          "b4_txtx/D");
        eventObsTree->Branch("b2_ttbar_leadPT_minDR_boosted",   &eventObsInputBDT.b2_ttbar_leadPT_minDR_boosted,    "b2_ttbar_leadPT_minDR_boosted/D");
        eventObsTree->Branch("b4_ttbar_leadPT_minDR_boosted",   &eventObsInputBDT.b4_ttbar_leadPT_minDR_boosted,    "b4_ttbar_leadPT_minDR_boosted/D");
        eventObsTree->Branch("tripleProductLeadingTopPTFrame",  &eventObsInputBDT.tripleProductLeadingTopPTFrame,   "tripleProductLeadingTopPTFrame/D");
        eventObsTree->Branch("train_score",     &eventObsInputBDT.train_score,      "train_score/I");
        
        // Iterate over events in this chain
        for(Int_t entry = 0; entry < nEntriesChainKt; ++entry) {
            treeReaderChainKt->ReadEntry(entry);
            
            // Apply an event selection rule
            if (Cuts::leadingTopPT<TRootLHEFParticle>(branchParticles, 0.)){
                // Compute all observables for this event
                std::for_each(observablesVec.begin(), observablesVec.end(), [&](auto& obs){obs->ComputeFillObservable(branchParticles, idxChain);});
                
                // Extract observable values from the vector into the variables to be written into TTree
                eventObsInputBDT.m_tttt                         = grabObsValue("m_tttt");
                eventObsInputBDT.m_tt                           = grabObsValue("m_tt");
                eventObsInputBDT.m_tbartbar                     = grabObsValue("m_tbartbar");
                eventObsInputBDT.m_ttbar_minDR                  = grabObsValue("m_ttbar_minDR");
                eventObsInputBDT.m_ttbar_leadPT_minDR           = grabObsValue("m_ttbar_leadPT_minDR");
                eventObsInputBDT.eta_tt                         = grabObsValue("eta_tt");
                eventObsInputBDT.eta_tbartbar                   = grabObsValue("eta_tbartbar");
                eventObsInputBDT.eta_ttbar_min                  = grabObsValue("eta_ttbar_min");
                eventObsInputBDT.eta_ttbar_max                  = grabObsValue("eta_ttbar_max");
                eventObsInputBDT.eta_ttbar_avg                  = grabObsValue("eta_ttbar_avg");
                eventObsInputBDT.phi_tt                         = grabObsValue("phi_tt");
                eventObsInputBDT.phi_tbartbar                   = grabObsValue("phi_tbartbar");
                eventObsInputBDT.phi_ttbar_min                  = grabObsValue("phi_ttbar_min");
                eventObsInputBDT.phi_ttbar_max                  = grabObsValue("phi_ttbar_max");
                eventObsInputBDT.phi_ttbar_avg                  = grabObsValue("phi_ttbar_avg");
                eventObsInputBDT.dy_tt                          = grabObsValue("dy_tt");
                eventObsInputBDT.dy_tbartbar                    = grabObsValue("dy_tbartbar");
                eventObsInputBDT.dy_ttbar_min                   = grabObsValue("dy_ttbar_min");
                eventObsInputBDT.dy_ttbar_max                   = grabObsValue("dy_ttbar_max");
                eventObsInputBDT.dy_ttbar_avg                   = grabObsValue("dy_ttbar_avg");
                eventObsInputBDT.ht                             = grabObsValue("HT");
                eventObsInputBDT.dR_ttbar_min                   = grabObsValue("dR_ttbar_min");
                eventObsInputBDT.dR_ttbar_avg                   = grabObsValue("dR_ttbar_avg");
                eventObsInputBDT.dRtt                           = grabObsValue("dRtt");
                eventObsInputBDT.dRtxtx                         = grabObsValue("dRtxtx");
                eventObsInputBDT.leadingTopPT                   = grabObsValue("leadingTopPT");
                eventObsInputBDT.diffHiLoTopPT                  = grabObsValue("diffHiLoTopPT");
                eventObsInputBDT.pT_ttbar_max                   = grabObsValue("pT_ttbar_max");
                eventObsInputBDT.pT_ttbar_minDR                 = grabObsValue("pT_ttbar_minDR");
                eventObsInputBDT.dR_ttbar_lead_min              = grabObsValue("dR_ttbar_lead_min");
                eventObsInputBDT.b2_tt                          = grabObsValue("b2_tt");
                eventObsInputBDT.b2_txtx                        = grabObsValue("b2_txtx");
                eventObsInputBDT.b4_tt                          = grabObsValue("b4_tt");
                eventObsInputBDT.b4_txtx                        = grabObsValue("b4_txtx");
                eventObsInputBDT.b2_ttbar_leadPT_minDR_boosted  = grabObsValue("b2_ttbar_leadPT_minDR_boosted");
                eventObsInputBDT.b4_ttbar_leadPT_minDR_boosted  = grabObsValue("b4_ttbar_leadPT_minDR_boosted");
                eventObsInputBDT.tripleProductLeadingTopPTFrame = grabObsValue("tripleProductLeadingTopPTFrame");
                // train_score is used by the XGBoost, assumes idx = 0 for CP-even, idx = 1 for CP-mixed, and idx = 2 for CP-odd
                eventObsInputBDT.train_score                    = idxChain/2;
                eventObsTree->Fill();
            }
        }

        // Write into TTree
        eventObsTree->Print();
        eventObsTree->Write();
        delete eventObsTree;
    }

    // Create plots for the observables
    std::cout << "Plotting observables...\n";
    std::for_each(observablesVec.begin(), observablesVec.end(), [&](auto& obs){obs->PlotAndSave();});
    delete hfile;
}

void processGenJetsFromDelphes(std::string productionName, std::string sample, std::string yukawa, std::string obsFilePath){
    // Initialize event chains
    std::vector<std::string> chainsNames;
    std::vector<TChain*> chains;

    //TChain chain_kt_0_alpha_0("Delphes");
    TChain chain_kt_1_alpha_0("Delphes");
    TChain chain_kt_2_alpha_0("Delphes");
    TChain chain_kt_5_alpha_0("Delphes");
    TChain chain_kt_1_alpha_45("Delphes");
    TChain chain_kt_1_alpha_90("Delphes");

    SampleSet sampleSet = samplemap.find(sample)->second;
    YukawaSet yukawaSet = yukawamap.find(yukawa)->second;

    switch (yukawaSet){
        case YukawaSet::kappa:
            // Used for sensitivity to top-Yukawa coupling strengths
            chainsNames = {"kt_1_alpha_0", "kt_2_alpha_0", "kt_5_alpha_0"};
            //create_chain_kt_0_alpha_0(chain_kt_0_alpha_0, sampleSet);
            create_chain_kt_1_alpha_0(chain_kt_1_alpha_0, sampleSet);
            create_chain_kt_2_alpha_0(chain_kt_2_alpha_0, sampleSet);
            create_chain_kt_5_alpha_0(chain_kt_5_alpha_0, sampleSet);

            //chains_kt.push_back(& chain_kt_0_alpha_0);
            chains.push_back(& chain_kt_1_alpha_0);
            chains.push_back(& chain_kt_2_alpha_0);
            chains.push_back(& chain_kt_5_alpha_0);
            break;

        case YukawaSet::alpha:
            // Used for sensitivity to top-Yukawa coupling CP property
            chainsNames = {"kt_1_alpha_0", "kt_1_alpha_45", "kt_1_alpha_90"};
            create_chain_kt_1_alpha_0(chain_kt_1_alpha_0, sampleSet);
            create_chain_kt_1_alpha_45(chain_kt_1_alpha_45, sampleSet);
            create_chain_kt_1_alpha_90(chain_kt_1_alpha_90, sampleSet);

            chains.push_back(& chain_kt_1_alpha_0);
            chains.push_back(& chain_kt_1_alpha_45);
            chains.push_back(& chain_kt_1_alpha_90);
            break;
    }

    // Set up observables into a vector 
    std::vector<std::unique_ptr<GeneralPlot>> observablesTruthJetMatch;

    observablesTruthJetMatch.emplace_back(new ObsJet_m_tttt(productionName, sampleSet, yukawaSet, chainsNames));
    observablesTruthJetMatch.emplace_back(new ObsJet_m_tttt(productionName, sampleSet, yukawaSet, chainsNames));
    observablesTruthJetMatch.emplace_back(new ObsJet_TMatchPerf_NumberOfTopsFullTMatch(productionName, sampleSet, yukawaSet, chainsNames));
    observablesTruthJetMatch.emplace_back(new ObsJet_TMatchPerf_NumberOfHadTopsFullTMatch(productionName, sampleSet, yukawaSet, chainsNames));
    observablesTruthJetMatch.emplace_back(new ObsJet_TMatchPerf_NumberOfLepTopsFullTMatch(productionName, sampleSet, yukawaSet, chainsNames));
    observablesTruthJetMatch.emplace_back(new ObsJet_TMatchPerf_NumberOfBJets(productionName, sampleSet, yukawaSet, chainsNames));
    observablesTruthJetMatch.emplace_back(new ObsJet_TMatchPerf_NumberOfLeptons(productionName, sampleSet, yukawaSet, chainsNames));
    observablesTruthJetMatch.emplace_back(new ObsJet_TMatchPerf_FourTopChannel(productionName, sampleSet, yukawaSet, chainsNames));
    observablesTruthJetMatch.emplace_back(new ObsJet_TMatchPerf_TopCategory(productionName, sampleSet, yukawaSet, chainsNames));
    observablesTruthJetMatch.emplace_back(new ObsJet_TMatchPerf_WCategory(productionName, sampleSet, yukawaSet, chainsNames));
    observablesTruthJetMatch.emplace_back(new ObsJet_TMatchPerf_DeltaRBJet(productionName, sampleSet, yukawaSet, chainsNames));
    observablesTruthJetMatch.emplace_back(new ObsJet_TMatchPerf_DeltaRQJet(productionName, sampleSet, yukawaSet, chainsNames));
    observablesTruthJetMatch.emplace_back(new ObsJet_TMatchPerf_DeltaRQjetQjet(productionName, sampleSet, yukawaSet, chainsNames));
    observablesTruthJetMatch.emplace_back(new ObsJet_TMatchPerf_QjetPT(productionName, sampleSet, yukawaSet, chainsNames));
    observablesTruthJetMatch.emplace_back(new ObsJet_TMatchPerf_QjetM(productionName, sampleSet, yukawaSet, chainsNames));
    observablesTruthJetMatch.emplace_back(new ObsJet_TMatchPerf_QjetEta(productionName, sampleSet, yukawaSet, chainsNames));
    observablesTruthJetMatch.emplace_back(new ObsJet_TMatchPerf_BjetPT(productionName, sampleSet, yukawaSet, chainsNames));
    observablesTruthJetMatch.emplace_back(new ObsJet_TMatchPerf_BjetM(productionName, sampleSet, yukawaSet, chainsNames));
    observablesTruthJetMatch.emplace_back(new ObsJet_TMatchPerf_BjetEta(productionName, sampleSet, yukawaSet, chainsNames));
    observablesTruthJetMatch.emplace_back(new ObsJet_TMatchPerf_WjetPT(productionName, sampleSet, yukawaSet, chainsNames));
    observablesTruthJetMatch.emplace_back(new ObsJet_TMatchPerf_WjetM(productionName, sampleSet, yukawaSet, chainsNames));
    observablesTruthJetMatch.emplace_back(new ObsJet_TMatchPerf_WjetEta(productionName, sampleSet, yukawaSet, chainsNames));
    observablesTruthJetMatch.emplace_back(new ObsJet_TMatchPerf_TMatchTopPT(productionName, sampleSet, yukawaSet, chainsNames));
    observablesTruthJetMatch.emplace_back(new ObsJet_TMatchPerf_TMatchTopM(productionName, sampleSet, yukawaSet, chainsNames));
    observablesTruthJetMatch.emplace_back(new ObsJet_TMatchPerf_TMatchTopEta(productionName, sampleSet, yukawaSet, chainsNames));
    observablesTruthJetMatch.emplace_back(new ObsJet_TMatchPerf_TopCategory_pt0_200(productionName, sampleSet, yukawaSet, chainsNames));
    observablesTruthJetMatch.emplace_back(new ObsJet_TMatchPerf_TopCategory_pt200_350(productionName, sampleSet, yukawaSet, chainsNames));
    observablesTruthJetMatch.emplace_back(new ObsJet_TMatchPerf_TopCategory_pt350_500(productionName, sampleSet, yukawaSet, chainsNames));
    observablesTruthJetMatch.emplace_back(new ObsJet_TMatchPerf_TopCategory_pt500(productionName, sampleSet, yukawaSet, chainsNames));
    
    // Variables to be written into the TTree
    typedef struct {
        Double_t numberOfTopsFullTMatch;
        Double_t numberOfHadTopsFullTMatch;
        Double_t numberOfLepTopsFullTMatch;
        Double_t numberOfBJets;
        Double_t numberOfLeptons;
        Double_t fourTopChannel;
        Double_t deltaRBJet;
        Double_t deltaRQJet;
        Double_t qjetPT;
        Double_t qjetEta;
        Double_t bjetPT;
        Double_t bjetM;
        Double_t bjetEta;
        Double_t wjetPT;
        Double_t wjetM;
        Double_t wjetEta;
        Double_t tMatchTopPT;
        Double_t tMatchTopM;
        Double_t tMatchTopEta;
    } EventTMatchObservables;

    // Helper function to extract the value of a given observable from the vector of observables
    auto grabObsValue = [&observablesTruthJetMatch](const char* name){
        auto it = std::find_if(
                observablesTruthJetMatch.begin(),
                observablesTruthJetMatch.end(),
                [&name](const std::unique_ptr<GeneralPlot>& obs){
                    return std::string(obs->pltparams.name) == std::string(name);
                }
            );
        if (it != std::end(observablesTruthJetMatch)){
            return (*it)->fillObservable;
        }
        else{
            return 0.;
        }
    };
    
    TFile *hfile = TFile::Open(obsFilePath.c_str(),"RECREATE"); 
    vector<TChain*>::iterator iTChain;

    // Iterate over the event chains (coupling strengths or CP-mixing angles)
    for(iTChain = chains.begin(); iTChain != chains.end(); iTChain++){
        int idxChain = iTChain - chains.begin();
        cout << "processing " << chainsNames.at(idxChain) << " ("  << idxChain+1 << "/" << chainsNames.size() << ")\n";

        ExRootTreeReader *treeReaderGenJets = new ExRootTreeReader(*iTChain);
        Long64_t nEntriesGenJets = treeReaderGenJets->GetEntries();
        
        TClonesArray *branchParticles = treeReaderGenJets->UseBranch("Particle");
        std::cout << "nEntriesGenJets " << nEntriesGenJets << "\n";
        TClonesArray *branchGenJet = treeReaderGenJets->UseBranch("GenJet");

        // Prepare output TTree
        EventTMatchObservables eventTMatchObs;
        
        const int nTops = 4;
        Int_t topCategories[nTops];
        Int_t topCategories_pt0_200[nTops];
        Int_t topCategories_pt200_350[nTops];
        Int_t topCategories_pt350_500[nTops];
        Int_t topCategories_pt500[nTops];
        Int_t wCategories[nTops];

        TTree *eventTMatchObsTree = new TTree(chainsNames.at(idxChain).c_str(), "Truth Match Observables");
        eventTMatchObsTree->Branch("numberOfTopsFullTMatch", &eventTMatchObs.numberOfTopsFullTMatch, "numberOfTopsFullTMatch/D");
        eventTMatchObsTree->Branch("numberOfHadTopsFullTMatch", &eventTMatchObs.numberOfHadTopsFullTMatch, "numberOfHadTopsFullTMatch/D");
        eventTMatchObsTree->Branch("numberOfLepTopsFullTMatch", &eventTMatchObs.numberOfLepTopsFullTMatch, "numberOfLepTopsFullTMatch/D");
        eventTMatchObsTree->Branch("numberOfBJets", &eventTMatchObs.numberOfBJets, "numberOfBJets/D");
        eventTMatchObsTree->Branch("numberOfLeptons", &eventTMatchObs.numberOfLeptons, "numberOfLeptons/D");
        eventTMatchObsTree->Branch("fourTopChannel", &eventTMatchObs.fourTopChannel, "fourTopChannel/D");
        eventTMatchObsTree->Branch("deltaRBJet", &eventTMatchObs.deltaRBJet, "deltaRBJet/D");
        eventTMatchObsTree->Branch("deltaRQJet", &eventTMatchObs.deltaRQJet, "deltaRQJet/D");
        eventTMatchObsTree->Branch("qjetPT", &eventTMatchObs.qjetPT, "qjetPT/D");
        eventTMatchObsTree->Branch("qjetEta", &eventTMatchObs.qjetEta, "qjetEta/D");
        eventTMatchObsTree->Branch("bjetPT", &eventTMatchObs.bjetPT, "bjetPT/D");
        eventTMatchObsTree->Branch("bjetM", &eventTMatchObs.bjetM, "bjetM/D");
        eventTMatchObsTree->Branch("bjetEta", &eventTMatchObs.bjetEta, "bjetEta/D");
        eventTMatchObsTree->Branch("wjetPT", &eventTMatchObs.wjetPT, "wjetPT/D");
        eventTMatchObsTree->Branch("wjetM", &eventTMatchObs.wjetM, "wjetM/D");
        eventTMatchObsTree->Branch("wjetEta", &eventTMatchObs.wjetEta, "wjetEta/D");
        eventTMatchObsTree->Branch("tMatchTopPT", &eventTMatchObs.tMatchTopPT, "tMatchTopPT/D");
        eventTMatchObsTree->Branch("tMatchTopM", &eventTMatchObs.tMatchTopM, "tMatchTopM/D");
        eventTMatchObsTree->Branch("tMatchTopEta", &eventTMatchObs.tMatchTopEta, "tMatchTopEta/D");
        eventTMatchObsTree->Branch("topCategories", topCategories, Form("topCategories[%d]/I", nTops));
        eventTMatchObsTree->Branch("topCategories_pt0_200", topCategories_pt0_200, Form("topCategories_pt0_200[%d]/I", nTops));
        eventTMatchObsTree->Branch("topCategories_pt200_350", topCategories_pt200_350, Form("topCategories_pt200_350[%d]/I", nTops));
        eventTMatchObsTree->Branch("topCategories_pt350_500", topCategories_pt350_500, Form("topCategories_pt350_500[%d]/I", nTops));
        eventTMatchObsTree->Branch("topCategories_pt500", topCategories_pt500, Form("topCategories_pt500[%d]/I", nTops));
        eventTMatchObsTree->Branch("wCategories", wCategories, Form("wCategories[%d]/I", nTops));
        
        // Iterate over events in this chain
        for(Int_t entry = 0; entry < nEntriesGenJets; ++entry) {
            treeReaderGenJets->ReadEntry(entry);
            TruthEvent4Top fourTopEvent(branchParticles, branchGenJet);

            // Apply an event selection rule
            if (fourTopEvent.getNumberLep() == 2){
                // Compute all observables for this event
                std::for_each(observablesTruthJetMatch.begin(), observablesTruthJetMatch.end(), [&](auto& obs){obs->ComputeFillObservable(&fourTopEvent, idxChain);});
                
                // Special treatment for the matching categories because these are stored as arrays
                auto derivedPtrTopCategory = dynamic_cast<ObsJet_TMatchPerf_TopCategory*>(observablesTruthJetMatch.at(8).get());
                auto derivedPtWCategory = dynamic_cast<ObsJet_TMatchPerf_WCategory*>(observablesTruthJetMatch.at(9).get());
                auto derivedPtrTopCategory_pt0_200 = dynamic_cast<ObsJet_TMatchPerf_TopCategory_pt0_200*>(observablesTruthJetMatch.at(10).get());
                auto derivedPtrTopCategory_pt200_350 = dynamic_cast<ObsJet_TMatchPerf_TopCategory_pt200_350*>(observablesTruthJetMatch.at(11).get());
                auto derivedPtrTopCategory_pt350_500 = dynamic_cast<ObsJet_TMatchPerf_TopCategory_pt350_500*>(observablesTruthJetMatch.at(12).get());
                auto derivedPtrTopCategory_pt500 = dynamic_cast<ObsJet_TMatchPerf_TopCategory_pt500*>(observablesTruthJetMatch.at(13).get());
                for(int i = 0; i<4; i++){
                    topCategories[i] = -1;
                    wCategories[i] = -1;
                    if (derivedPtrTopCategory){
                        topCategories[i] = derivedPtrTopCategory->categories[i];
                    }
                    if(derivedPtWCategory){
                        wCategories[i] = derivedPtWCategory->categories[i];
                    }
                    if (derivedPtrTopCategory_pt0_200){
                        topCategories_pt0_200[i] = derivedPtrTopCategory_pt0_200->categories[i];
                    }
                    if (derivedPtrTopCategory_pt200_350){
                        topCategories_pt200_350[i] = derivedPtrTopCategory_pt200_350->categories[i];
                    }
                    if (derivedPtrTopCategory_pt350_500){
                        topCategories_pt350_500[i] = derivedPtrTopCategory_pt350_500->categories[i];
                    }
                    if (derivedPtrTopCategory_pt500){
                        topCategories_pt500[i] = derivedPtrTopCategory_pt500->categories[i];
                    }
                }

                // Extract observable values from the vector into the variables to be written into TTree
                eventTMatchObs.numberOfTopsFullTMatch = grabObsValue("numberofTopsFullTMatch");
                eventTMatchObs.numberOfHadTopsFullTMatch = grabObsValue("numberofHadTopsFullTMatch");
                eventTMatchObs.numberOfLepTopsFullTMatch = grabObsValue("numberofLepTopsFullTMatch");
                eventTMatchObs.numberOfBJets = grabObsValue("numberofBJets");
                eventTMatchObs.numberOfLeptons = grabObsValue("numberofLeptons");
                eventTMatchObs.fourTopChannel = grabObsValue("fourTopChannel");
                eventTMatchObs.deltaRBJet = grabObsValue("deltaRBJet");
                eventTMatchObs.deltaRQJet = grabObsValue("deltaRQJet");
                eventTMatchObs.qjetPT = grabObsValue("qjetPT");
                eventTMatchObs.qjetEta = grabObsValue("qjetEta");
                eventTMatchObs.bjetPT = grabObsValue("bjetPT");
                eventTMatchObs.bjetM = grabObsValue("bjetM");
                eventTMatchObs.bjetEta = grabObsValue("bjetEta");
                eventTMatchObs.wjetPT = grabObsValue("wjetPT");
                eventTMatchObs.wjetM = grabObsValue("wjetM");
                eventTMatchObs.wjetEta = grabObsValue("wjetEta");
                eventTMatchObs.tMatchTopPT = grabObsValue("tMatchTopPT");
                eventTMatchObs.tMatchTopM = grabObsValue("tMatchTopM");
                eventTMatchObs.tMatchTopEta = grabObsValue("tMatchTopEta");
                eventTMatchObsTree->Fill();
            }
        }

        // Write into TTree
        eventTMatchObsTree->Print();
        eventTMatchObsTree->Write();
        delete eventTMatchObsTree;
    }

    // Create plots for the observables
    std::cout << "Plotting observables...\n";
    std::for_each(observablesTruthJetMatch.begin(), observablesTruthJetMatch.end(), [&](auto& obs){obs->PlotAndSave();});
    delete hfile;
}

void MacroMain(std::string sample, std::string yukawa){
    std::string productionName = "prod220222_1M_run230922";
    std::string obsFileBaseName = "observables.root";

    SampleSet sampleSet = samplemap.find(sample)->second;
    YukawaSet yukawaSet = yukawamap.find(yukawa)->second;

    std::cout << "Macro is starting for production " << productionName << " " << sampleSetToStr(sampleSet) << "\n";
    std::string mkdirCommand = std::string("mkdir -p ../workspaces/") + productionName + std::string("/plots_all-observables");
    system(mkdirCommand.c_str());
    
    const char* chainName = "";
    if(sampleSetToStr(sampleSet) == ("MGPY8Delphes4TopsInclusive")){
        // Running with GenJets from Delphes
        std::string obsFilePath = std::string("../workspaces/") + productionName + std::string("/jet_") + obsFileBaseName;
        processGenJetsFromDelphes(productionName, sample, yukawa, obsFilePath);
    }
    else{
        // Running with partons from MadGraph
        std::string obsFilePath = std::string("../workspaces/") + productionName + std::string("/parton_") + obsFileBaseName;
        processPartonsFromMadGraph(productionName, sample, yukawa, obsFilePath);
    }
}

int main(){
    return 0;
}
